/* oxlint-disable unicorn/no-empty-file */
// ==UserScript==
// @match       https://*.miniblox.io/*
// @match       https://*.miniblox.online/*
// @match       https://*.bloxbattles.io/*
// @match       https://*.miniblox.org/*
//#region mirrors (updated automatically by scripts/mirrors.ts, do NOT REDEEM)
// @match       https://*.classcraft.pro/*
// @match       https://*.mathnest.space/*
// @match       https://*.storyhall.site/*
//#endregion
// @run-at      document-idle
// ==/UserScript==

/**
 * All of the code by here is generated by Rolldown, view our source at https://codeberg.org/Miniblox/VapeRewrite.
 */
