// ==UserScript==
// @name        Vape Rewrite
// @namespace   https://codeberg.org/Miniblox
// @description The Vape UserScript, but rewritten.
// @license     AGPL-3.0-or-later
// @match       https://miniblox.io/*
// @match       https://miniblox.org/*
// @match       https://miniblox.online/*
// @match       https://bloxbattles.io/*
// @icon        https://miniblox.io/favicon.png
// @grant       GM_addStyle
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       unsafeWindow
// @version     process.env.VERSION
// @author      process.env.AUTHOR
// @require     https://cdn.jsdelivr.net/npm/@violentmonkey/dom@2
// @require     https://github.com/6x68/vm-ui/releases/download/v0.9.7-1/index.js
// @resource    bind https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/bind.png
// @run-at      document-start
// ==/UserScript==

/**
 * All of the code by here is generated by Rollup, view our source at https://codeberg.org/Miniblox/VapeRewrite.
 */
