// ==UserScript==
// @name        epaV Rewrite
// @namespace   https://b.ab/
// @description This is a userscript.
// @license     AGPL-3.0-or-later
// @match       https://miniblox.io/*
// @match       https://miniblox.org/*
// @match       https://miniblox.online/*
// @match       https://bloxbattles.io/*
// @icon        https://miniblox.io/favicon.png
// @grant       GM_addStyle
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       unsafeWindow
// @version     process.env.VERSION
// @author      process.env.AUTHOR
// @require     https://cdn.jsdelivr.net/npm/@violentmonkey/dom@2
// @require     https://github.com/6x68/vm-ui/releases/download/v0.9.7-1/index.js
// @run-at      document-start
// ==/UserScript==

/**
 * All of the code by here is generated by Rollup, view our source somewhere else.
 */
