name: Build

on:
  push:
    paths:
      - packages/**
      - package.json
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install
        run: bun install

      - name: Build
        run: bunx rolldown -c

      - name: Upload artifacts
        uses: forgejo/upload-artifact@v5
        with:
          path: dist/*/*.user.js
