// ==UserScript==
// @name        Vape Rewrite
// @namespace   https://codeberg.org/Miniblox
// @description The Vape UserScript, but rewritten.
// @license     AGPL-3.0-or-later
// @match       https://miniblox.io/*
// @match       https://miniblox.org/*
// @match       https://miniblox.online/*
// @match       https://bloxbattles.io/*
// @match       https://blockcraft.victorwei.com/*
// @match       https://blockcraft.online/*
// @icon        https://miniblox.io/favicon.png
// @grant       GM_addStyle
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       unsafeWindow
// @version     process.env.VERSION
// @author      process.env.AUTHOR
// @require     https://cdn.jsdelivr.net/npm/@violentmonkey/dom@2
// @require     https://cdn.jsdelivr.net/npm/@wq2/ui@0.10.1
// @resource    bind https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/bind.png
// @resource    combat https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/combat.png
// @resource    blatant https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/blatant.png
// @resource    minigames https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/minigames.png
// @resource    profiles https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/profiles.png
// @resource    utility https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/utility.png
// @resource    inventory https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/inventory.png
// @resource    render https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/render.png
// @resource    world https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/categories/world.png
// @run-at      document-start
// ==/UserScript==

/**
 * All of the code by here is generated by Rollup, view our source at https://codeberg.org/Miniblox/VapeRewrite.
 */
