// ==UserScript==
// @name        process.env.NAME
// @namespace   https://codeberg.org/Miniblox
// @description The Vape UserScript, but rewritten.
// @license     AGPL-3.0-or-later
// @homepageURL https://codeberg.org/Miniblox/VapeRewrite
// @match       https://miniblox.io/*
// @match       https://miniblox.org/*
// @match       https://miniblox.online/*
// @match       https://bloxbattles.io/*
// @match       https://blockcraft.victorwei.com/*
// @match       https://blockcraft.online/*
// @icon        https://miniblox.io/favicon.png
// @grant       GM_addStyle
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       unsafeWindow
// @version     process.env.VERSION
// @author      process.env.AUTHOR
// @require     https://cdn.jsdelivr.net/npm/@violentmonkey/dom@2
// @require     https://cdn.jsdelivr.net/npm/@wq2/ui@0.10.5
// @resource    bind https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/bind.png
// @resource    expand https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/expand.png
// @resource    expand-right https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/expand-right.png
// @resource    contract https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/contract.png
// @resource    combat https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/combat.png
// @resource    blatant https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/blatant.png
// @resource    minigames https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/minigames.png
// @resource    guivape https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/gui/vape.png
// @resource    guiv4 https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/gui/v4.png
// @resource    guisettings https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/gui/settings.png
// @resource    overlay-tab https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/overlays/tab.png
// @resource    dots https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/dots.png
// @resource    profilesicon https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/profiles.png
// @resource    close https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/close.png
// @resource    add https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/misc/add.png
// @resource    textvape https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/textvape.png
// @resource    textv4 https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/textv4.png
// @resource    info https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/notifications/info.png
// @resource    warning https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/notifications/warning.png
// @resource    alert https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/notifications/alert.png
// @resource    rainbow_1 https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/rainbow/1.png
// @resource    utility https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/utility.png
// @resource    inventory https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/inventory.png
// @resource    render https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/render.png
// @resource    world https://codeberg.org/Miniblox/VapeRewrite/raw/branch/main/icons/category/world.png
// @run-at      document-start
// ==/UserScript==

/**
 * All of the code by here is generated by Rollup, view our source at https://codeberg.org/Miniblox/VapeRewrite.
 */
